# Generated by Django 4.2.25 on 2025-10-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_profile_delete_order_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10, verbose_name='Остаток на складе'),
        ),
    ]
