# Generated by Django 4.2.25 on 2025-12-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_status_order_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда подписался')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Уведомление о поступлении',
                'verbose_name_plural': 'Уведомления о поступлении',
                'unique_together': {('product', 'email')},
            },
        ),
    ]
